# Generated by Django 4.1.5 on 2023-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
